import type { Metadata } from 'next'
import { Inter, Rubik_Glitch } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] });
export const rubikGlitch = Rubik_Glitch({weight: '400', subsets: ['latin-ext'], variable:"--font-rubik-glitch"});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' ' + rubikGlitch.className}>{children}</body>
    </html>
  )
}
